[srt_cam_push]
device=/dev/video0
host=10.215.182.17
port=9000
width=1280
height=720
fps=25
bitrate=2000
gop=50
profile=baseline
latency=120
audio=1
audio_device=plughw:3,0
audio_bitrate=128
audio_codec=aac
ctrl_port=10090
